apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app

spec:
   containers:
   - name: worker-apps
     image: dockersamples/dockersamples/examplevotingapp_worker
     ports:
     - containerPort: 80
